version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: lab-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: lab-management-system
    volumes:
      - mongodb_data:/data/db
    networks:
      - lab-network

  # Backend API Server
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: lab-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/lab-management-system
      - CORS_ORIGINS=http://localhost:5173,http://frontend:5173
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=your_access_key_here
      - AWS_SECRET_ACCESS_KEY=your_secret_key_here
      - AWS_S3_BUCKET_NAME=lab-management-reports
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - lab-network
    command: sh -c "sleep 10 && npm run dev"

  # Frontend React App
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: lab-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - lab-network

volumes:
  mongodb_data:

networks:
  lab-network:
    driver: bridge 